#################### BASIC ##############################

connected = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"","position":[265,54],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}
not_connected = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[401,54],"accepting":False,"petri_type":"place"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}

strongly_connected = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[415,156],"accepting":False,"petri_type":"place"},{"label":"","position":[236,183],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":3,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}
not_strongly_connected = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[415,156],"accepting":False,"petri_type":"place"},{"label":"","position":[236,183],"accepting":False,"petri_type":"transition"},{"label":"","position":[493,54],"accepting":False,"petri_type":"place"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":3,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":4,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}

transition_degree_one = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[386,167],"accepting":False,"petri_type":"place"},{"label":"","position":[233,188],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":3,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}
not_transition_degree_one = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"a","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[386,167],"accepting":False,"petri_type":"place"},{"label":"","position":[233,188],"accepting":False,"petri_type":"transition"},{"label":"","position":[414,28],"accepting":False,"petri_type":"place"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":3,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":4,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}

# TODO
node_on_shortest_path = 0
not_node_on_shortest_path = 0

node_label_exists = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"a","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[402,73],"accepting":False,"petri_type":"place"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}
not_node_label_exists = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[402,73],"accepting":False,"petri_type":"place"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}

node_empty_label = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"","position":[265,54],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}
not_node_empty_label = {"_version":1,"vertices":[{"label":"a","position":[138,54],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}

arc_missing = {"_version":1,"vertices":[{"label":"a","position":[138,54],"accepting":False,"petri_type":"place"},{"label":"","position":[265,54],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}}]}
not_arc_missing = {"_version":1,"vertices":[{"label":"a","position":[138,54],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}}]}

arc_has_label = {"_version":1,"vertices":[{"label":"a","position":[138,54],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"ab","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}}]}
not_arc_has_label = {"_version":1,"vertices":[{"label":"a","position":[138,54],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"a","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}}]}

at_most_one_arc = {"_version":1,"vertices":[{"label":"a","position":[138,54],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[308,174],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}},{"from":0,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.7200923787528867,"perpendicularPart":63.14681013705275}}]}
not_at_most_one_arc = {"_version":1,"vertices":[{"label":"a","position":[131,67],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[308,174],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}},{"from":0,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.7200923787528867,"perpendicularPart":63.14681013705275}},{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":16}}]}


#################### FUNCTIONALITY ##############################
# These test cases were written with the old UI: place label holds number of tokens
number_of_tokens = {"_version":1,"vertices":[{"label":"abc","position":[58,80],"accepting":false,"petri_type":"place"},{"label":"0","position":[276,118],"accepting":false,"petri_type":"place"},{"label":"","position":[160,80],"accepting":false,"petri_type":"transition"},{"label":"4","position":[455,92],"accepting":false,"petri_type":"place"},{"label":"","position":[324,194],"accepting":false,"petri_type":"transition"}],"edges":[{"from":0,"to":2,"label":"e0","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":1,"label":"e1","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":4,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":4,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":3.141592653589793,"parallelPart":0.6975071413002327,"perpendicularPart":-30.395201953672565}}]}
not_number_of_tokens = {"_version":1,"vertices":[{"label":"abc","position":[58,80],"accepting":false,"petri_type":"place"},{"label":"0","position":[276,118],"accepting":false,"petri_type":"place"},{"label":"","position":[160,80],"accepting":false,"petri_type":"transition"},{"label":"3","position":[455,92],"accepting":false,"petri_type":"place"},{"label":"","position":[324,194],"accepting":false,"petri_type":"transition"}],"edges":[{"from":0,"to":2,"label":"e0","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":1,"label":"e1","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":4,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":4,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":3.141592653589793,"parallelPart":0.6975071413002327,"perpendicularPart":-30.395201953672565}}]}

# possible_sequence seems to work
# impossible_sequence seems to work
# marking_given


# Not sure what a workflow net is so did not test it extensively
workflow_net = {"_version":1,"vertices":[{"label":"abc","position":[58,80],"accepting":false,"petri_type":"place"},{"label":"0","position":[276,118],"accepting":false,"petri_type":"place"},{"label":"","position":[160,80],"accepting":false,"petri_type":"transition"},{"label":"3","position":[455,92],"accepting":false,"petri_type":"place"},{"label":"","position":[324,194],"accepting":false,"petri_type":"transition"}],"edges":[{"from":0,"to":2,"label":"e0","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":1,"label":"e1","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":4,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":4,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":3.141592653589793,"parallelPart":0.6975071413002327,"perpendicularPart":-30.395201953672565}}]}
not_workflow_net = {"_version":1,"vertices":[{"label":"abc","position":[58,80],"accepting":false,"petri_type":"place"},{"label":"0","position":[276,118],"accepting":false,"petri_type":"place"},{"label":"","position":[160,80],"accepting":false,"petri_type":"transition"},{"label":"3","position":[455,92],"accepting":false,"petri_type":"place"},{"label":"","position":[324,194],"accepting":false,"petri_type":"transition"},{"label":"","position":[333,289],"accepting":false,"petri_type":"transition"}],"edges":[{"from":0,"to":2,"label":"e0","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":1,"label":"e1","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":4,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":4,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":3.141592653589793,"parallelPart":0.6975071413002327,"perpendicularPart":-30.395201953672565}},{"from":3,"to":5,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5907287728381725,"perpendicularPart":-60.068833708661614}},{"from":5,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5761571086114696,"perpendicularPart":-124.87007852626739}}]}


#################### BEHAVIOUR ##############################
bounded = {"_version":1,"vertices":[{"label":"a","position":[131,67],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[296,148],"accepting":False,"petri_type":"place"},{"label":"","position":[163,179],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":3,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}
not_bounded = {"_version":1,"vertices":[{"label":"a","position":[131,67],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[296,148],"accepting":False,"petri_type":"place"},{"label":"","position":[163,179],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":3,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":16}}]}

infinite = {"_version":1,"vertices":[{"label":"a","position":[131,67],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[296,148],"accepting":False,"petri_type":"place"},{"label":"","position":[163,179],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":3,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":16}}]}
not_infinite = {"_version":1,"vertices":[{"label":"a","position":[131,67],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[296,148],"accepting":False,"petri_type":"place"},{"label":"","position":[163,179],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":3,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}

# TODO: deadlock free seems to not work
# deadlock_free =
# not_deadlock_free =


## DESIGN ###

# no_forbidden_words works
# only_mandatory_words works
# no_duplicate_label works
# left_to_right works
# top_to_bottom works
# horizontally_adjacent works
# vertically_adjacent works
# list_left_of works
# list_above_of works

# This should contain exactly 5 crossings, tests only curved edges
crossing_arcs = {"_version":1,"vertices":[{"label":"a","position":[288,189],"accepting":false,"petri_type":"place"},{"label":"b","position":[535,189],"accepting":false,"petri_type":"transition"},{"label":"c","position":[298,27],"accepting":false,"petri_type":"transition"},{"label":"d","position":[49,172],"accepting":false,"petri_type":"transition"},{"label":"e","position":[288,373],"accepting":false,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":3.141592653589793,"parallelPart":0.6153846153846154,"perpendicularPart":-87}},{"from":0,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.43767081688430004,"perpendicularPart":95.80529986031056}},{"from":0,"to":4,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.375,"perpendicularPart":-81}},{"from":0,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5002961156592928,"perpendicularPart":-118.80444000976476}},{"from":0,"to":2,"label":"","bend":{"lineAngleAdjust":3.141592653589793,"parallelPart":0.4417704221075008,"perpendicularPart":-120.64690558614798}},{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.15384615384615385,"perpendicularPart":95}},{"from":0,"to":4,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.09782608695652174,"perpendicularPart":123}},{"from":0,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.7453579515763804,"perpendicularPart":86.54702706676356}}]}

# This should contain exactly 11 crossing, tests only straight edges
crossing_arcs_straight = {"_version":1,"vertices":[{"label":"a","position":[298,189],"accepting":false,"petri_type":"place"},{"label":"b","position":[535,189],"accepting":false,"petri_type":"transition"},{"label":"c","position":[298,27],"accepting":false,"petri_type":"transition"},{"label":"d","position":[49,172],"accepting":false,"petri_type":"transition"},{"label":"e","position":[288,373],"accepting":false,"petri_type":"transition"},{"label":"h","position":[438,304],"accepting":false,"petri_type":"place"},{"label":"f","position":[147,61],"accepting":false,"petri_type":"place"},{"label":"g","position":[428,75],"accepting":false,"petri_type":"place"},{"label":"i","position":[105,290],"accepting":false,"petri_type":"place"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":0,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":0,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":0,"to":4,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":5,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":5,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":6,"to":4,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":7,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":8,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":5,"to":4,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":5,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}

# Tests all type of intersections, should be 12
crossing_arcs_all = {"_version":1,"vertices":[{"label":"a","position":[262,164],"accepting":false,"petri_type":"place"},{"label":"b","position":[459,170],"accepting":false,"petri_type":"transition"},{"label":"d","position":[62,158],"accepting":false,"petri_type":"transition"},{"label":"c","position":[278,43],"accepting":false,"petri_type":"transition"},{"label":"e","position":[262,300],"accepting":false,"petri_type":"transition"},{"label":"","position":[435,28],"accepting":false,"petri_type":"transition"},{"label":"","position":[49,82],"accepting":false,"petri_type":"place"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":0,"to":4,"label":"","bend":{"lineAngleAdjust":3.141592653589793,"parallelPart":0.35294117647058826,"perpendicularPart":-130}},{"from":0,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.4237765993152984,"perpendicularPart":139.42273246684888}},{"from":0,"to":5,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":0,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":0,"to":3,"label":"","bend":{"lineAngleAdjust":3.141592653589793,"parallelPart":0.1799019936900047,"perpendicularPart":-139.07862041633425}},{"from":6,"to":5,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5292406129864659,"perpendicularPart":77.32472565172229}},{"from":4,"to":6,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":0,"to":4,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.4264705882352941,"perpendicularPart":114}}]}