#################### BASIC ##############################

connected = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"","position":[265,54],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}
not_connected = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[401,54],"accepting":False,"petri_type":"place"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}

strongly_connected = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[415,156],"accepting":False,"petri_type":"place"},{"label":"","position":[236,183],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":3,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}
not_strongly_connected = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[415,156],"accepting":False,"petri_type":"place"},{"label":"","position":[236,183],"accepting":False,"petri_type":"transition"},{"label":"","position":[493,54],"accepting":False,"petri_type":"place"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":3,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":4,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}

transition_degree_one = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[386,167],"accepting":False,"petri_type":"place"},{"label":"","position":[233,188],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":3,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}
not_transition_degree_one = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"a","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[386,167],"accepting":False,"petri_type":"place"},{"label":"","position":[233,188],"accepting":False,"petri_type":"transition"},{"label":"","position":[414,28],"accepting":False,"petri_type":"place"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":3,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":4,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}

# TODO
node_on_shortest_path = 0
not_node_on_shortest_path = 0

node_label_exists = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"a","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[402,73],"accepting":False,"petri_type":"place"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}
not_node_label_exists = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[402,73],"accepting":False,"petri_type":"place"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}

node_empty_label = {"_version":1,"vertices":[{"label":"","position":[140,59],"accepting":False,"petri_type":"place"},{"label":"","position":[265,54],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}
not_node_empty_label = {"_version":1,"vertices":[{"label":"a","position":[138,54],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}

arc_missing = {"_version":1,"vertices":[{"label":"a","position":[138,54],"accepting":False,"petri_type":"place"},{"label":"","position":[265,54],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}}]}
not_arc_missing = {"_version":1,"vertices":[{"label":"a","position":[138,54],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}}]}

arc_has_label = {"_version":1,"vertices":[{"label":"a","position":[138,54],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"ab","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}}]}
not_arc_has_label = {"_version":1,"vertices":[{"label":"a","position":[138,54],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"a","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}}]}

at_most_one_arc = {"_version":1,"vertices":[{"label":"a","position":[138,54],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[308,174],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}},{"from":0,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.7200923787528867,"perpendicularPart":63.14681013705275}}]}
not_at_most_one_arc = {"_version":1,"vertices":[{"label":"a","position":[131,67],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[308,174],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}},{"from":0,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.7200923787528867,"perpendicularPart":63.14681013705275}},{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":16}}]}


#################### FUNCTIONALITY ##############################
# TODO: need UI with tokens to test this easily



#################### BEHAVIOUR ##############################
bounded = {"_version":1,"vertices":[{"label":"a","position":[131,67],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[296,148],"accepting":False,"petri_type":"place"},{"label":"","position":[163,179],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":3,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}
not_bounded = {"_version":1,"vertices":[{"label":"a","position":[131,67],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[296,148],"accepting":False,"petri_type":"place"},{"label":"","position":[163,179],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":3,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":16}}]}

infinite = {"_version":1,"vertices":[{"label":"a","position":[131,67],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[296,148],"accepting":False,"petri_type":"place"},{"label":"","position":[163,179],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":3,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":1,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":16}}]}
not_infinite = {"_version":1,"vertices":[{"label":"a","position":[131,67],"accepting":False,"petri_type":"place"},{"label":"b","position":[265,54],"accepting":False,"petri_type":"transition"},{"label":"","position":[296,148],"accepting":False,"petri_type":"place"},{"label":"","position":[163,179],"accepting":False,"petri_type":"transition"}],"edges":[{"from":0,"to":1,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5275590551181102,"perpendicularPart":0}},{"from":1,"to":2,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":2,"to":3,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}},{"from":3,"to":0,"label":"","bend":{"lineAngleAdjust":0,"parallelPart":0.5,"perpendicularPart":0}}]}

